// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/list-blog-posts.ts
import { createClient } from "npm:@supabase/supabase-js@^2.89.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^3.25.76";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_blog_posts_default = defineTool({
  name: "list_blog_posts",
  title: "List blog posts",
  description: "List all published saffron blog posts, most recent first. Returns title, author, excerpt, creation date, and post ID.",
  inputSchema: {
    limit: z.number().int().min(1).max(50).optional().describe("Max number of posts to return (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated." }], isError: true };
    }
    const { data, error } = await supabaseForUser(ctx).from("blog_posts").select("id, title, excerpt, author_name, created_at, updated_at, user_id").order("created_at", { ascending: false }).limit(limit ?? 20);
    if (error) {
      return { content: [{ type: "text", text: `Error: ${error.message}` }], isError: true };
    }
    const currentUserId = ctx.getUserId();
    const items = (data ?? []).map((p) => ({
      id: p.id,
      title: p.title,
      excerpt: p.excerpt,
      author: p.author_name,
      created_at: p.created_at,
      updated_at: p.updated_at,
      is_yours: p.user_id === currentUserId
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(items, null, 2) }],
      structuredContent: { posts: items, total: items.length }
    };
  }
});

// src/lib/mcp/tools/get-blog-post.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.89.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z2 } from "npm:zod@^3.25.76";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_blog_post_default = defineTool2({
  name: "get_blog_post",
  title: "Get blog post",
  description: "Fetch the full content of a single saffron blog post by its ID (title, author, excerpt, and full body).",
  inputSchema: {
    id: z2.string().uuid().describe("The UUID of the blog post to fetch.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated." }], isError: true };
    }
    const { data, error } = await supabaseForUser2(ctx).from("blog_posts").select("id, title, excerpt, content, author_name, created_at, updated_at, user_id").eq("id", id).maybeSingle();
    if (error) return { content: [{ type: "text", text: `Error: ${error.message}` }], isError: true };
    if (!data) return { content: [{ type: "text", text: `No blog post found with id ${id}.` }], isError: true };
    const post = {
      id: data.id,
      title: data.title,
      excerpt: data.excerpt,
      content: data.content,
      author: data.author_name,
      created_at: data.created_at,
      updated_at: data.updated_at,
      is_yours: data.user_id === ctx.getUserId()
    };
    return {
      content: [{ type: "text", text: JSON.stringify(post, null, 2) }],
      structuredContent: { post }
    };
  }
});

// src/lib/mcp/tools/create-blog-post.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.89.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z3 } from "npm:zod@^3.25.76";
function supabaseForUser3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var create_blog_post_default = defineTool3({
  name: "create_blog_post",
  title: "Create blog post",
  description: "Create a new saffron blog post authored by the signed-in user. Requires a title, short excerpt, and full post content.",
  inputSchema: {
    title: z3.string().trim().min(1).max(200).describe("Post title."),
    excerpt: z3.string().trim().min(1).max(500).describe("Short summary shown on the blog listing."),
    content: z3.string().trim().min(1).describe("Full post body (plain text or markdown)."),
    author_name: z3.string().trim().min(1).max(100).optional().describe("Optional display name for the author. Defaults to the signed-in user's email.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ title, excerpt, content, author_name }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated." }], isError: true };
    }
    const fallbackName = ctx.getUserEmail() ?? "Anonymous";
    const { data, error } = await supabaseForUser3(ctx).from("blog_posts").insert({
      user_id: ctx.getUserId(),
      title,
      excerpt,
      content,
      author_name: author_name ?? fallbackName
    }).select("id, title, excerpt, author_name, created_at").single();
    if (error) {
      return { content: [{ type: "text", text: `Error creating post: ${error.message}` }], isError: true };
    }
    return {
      content: [{ type: "text", text: `Created blog post "${data.title}" (id: ${data.id}).` }],
      structuredContent: { post: data }
    };
  }
});

// src/lib/mcp/tools/update-blog-post.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.89.0";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z4 } from "npm:zod@^3.25.76";
function supabaseForUser4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var update_blog_post_default = defineTool4({
  name: "update_blog_post",
  title: "Update blog post",
  description: "Update one of the signed-in user's own blog posts. Only fields provided are changed. Users cannot edit other authors' posts.",
  inputSchema: {
    id: z4.string().uuid().describe("The UUID of the blog post to update."),
    title: z4.string().trim().min(1).max(200).optional().describe("New post title."),
    excerpt: z4.string().trim().min(1).max(500).optional().describe("New excerpt."),
    content: z4.string().trim().min(1).optional().describe("New full post body."),
    author_name: z4.string().trim().min(1).max(100).optional().describe("New display name for the author.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ id, title, excerpt, content, author_name }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated." }], isError: true };
    }
    const patch = { updated_at: (/* @__PURE__ */ new Date()).toISOString() };
    if (title !== void 0) patch.title = title;
    if (excerpt !== void 0) patch.excerpt = excerpt;
    if (content !== void 0) patch.content = content;
    if (author_name !== void 0) patch.author_name = author_name;
    if (Object.keys(patch).length === 1) {
      return { content: [{ type: "text", text: "Nothing to update \u2014 provide at least one field." }], isError: true };
    }
    const { data, error } = await supabaseForUser4(ctx).from("blog_posts").update(patch).eq("id", id).eq("user_id", ctx.getUserId()).select("id, title, excerpt, author_name, updated_at").maybeSingle();
    if (error) {
      return { content: [{ type: "text", text: `Error updating post: ${error.message}` }], isError: true };
    }
    if (!data) {
      return {
        content: [{ type: "text", text: `No post found with id ${id} that you own. You can only edit your own posts.` }],
        isError: true
      };
    }
    return {
      content: [{ type: "text", text: `Updated blog post "${data.title}".` }],
      structuredContent: { post: data }
    };
  }
});

// src/lib/mcp/tools/delete-blog-post.ts
import { createClient as createClient5 } from "npm:@supabase/supabase-js@^2.89.0";
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z5 } from "npm:zod@^3.25.76";
function supabaseForUser5(ctx) {
  return createClient5(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var delete_blog_post_default = defineTool5({
  name: "delete_blog_post",
  title: "Delete blog post",
  description: "Permanently delete one of the signed-in user's own blog posts. Users cannot delete other authors' posts.",
  inputSchema: {
    id: z5.string().uuid().describe("The UUID of the blog post to delete.")
  },
  annotations: { readOnlyHint: false, destructiveHint: true, openWorldHint: false },
  handler: async ({ id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated." }], isError: true };
    }
    const { data, error } = await supabaseForUser5(ctx).from("blog_posts").delete().eq("id", id).eq("user_id", ctx.getUserId()).select("id, title").maybeSingle();
    if (error) {
      return { content: [{ type: "text", text: `Error deleting post: ${error.message}` }], isError: true };
    }
    if (!data) {
      return {
        content: [{ type: "text", text: `No post found with id ${id} that you own. You can only delete your own posts.` }],
        isError: true
      };
    }
    return {
      content: [{ type: "text", text: `Deleted blog post "${data.title}".` }],
      structuredContent: { deleted: data }
    };
  }
});

// src/lib/mcp/tools/list-my-posts.ts
import { createClient as createClient6 } from "npm:@supabase/supabase-js@^2.89.0";
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z6 } from "npm:zod@^3.25.76";
function supabaseForUser6(ctx) {
  return createClient6(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_my_posts_default = defineTool6({
  name: "list_my_blog_posts",
  title: "List my blog posts",
  description: "List only the blog posts authored by the signed-in user, most recent first.",
  inputSchema: {
    limit: z6.number().int().min(1).max(50).optional().describe("Max number of posts to return (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated." }], isError: true };
    }
    const { data, error } = await supabaseForUser6(ctx).from("blog_posts").select("id, title, excerpt, author_name, created_at, updated_at").eq("user_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(limit ?? 20);
    if (error) {
      return { content: [{ type: "text", text: `Error: ${error.message}` }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { posts: data ?? [], total: (data ?? []).length }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "fjczrrbaozfnntqixqpc";
var mcp_default = defineMcp({
  name: "crocus-sativus-mcp",
  title: "Crocus Sativus Blog MCP",
  version: "0.1.0",
  instructions: "Read and manage saffron blog posts on the Crocus Sativus site. Use list_blog_posts and get_blog_post to browse, list_my_blog_posts to see your own posts, and create_blog_post / update_blog_post / delete_blog_post to publish or edit your contributions. Only the signed-in user's own posts can be modified.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    list_blog_posts_default,
    get_blog_post_default,
    list_my_posts_default,
    create_blog_post_default,
    update_blog_post_default,
    delete_blog_post_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
