// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jgtewrposvultcrghyuo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpndGV3cnBvc3Z1bHRjcmdoeXVvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYwMzYyODQsImV4cCI6MjA3MTYxMjI4NH0.ZpJmcNuG3LF6JfCZh-KxhLFaFAolBusOc8-n3Wkzg8I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});